remove unused "postcss" declaration from package.json
I think that I added it unknowingly when copying from CodeSandbox.

This fixes Vue problem:

```
 ERROR  Failed to compile with 1 error                                                                                                                                                  17:48:35

 error  in ../node_modules/handsontable/dist/handsontable.full.css

Error: No PostCSS Config found in: /Users/warp/www/handsontable/examples/11.1.0/docs/vue/node_modules/handsontable/dist

 @ ../node_modules/cache-loader/dist/cjs.js??ref--13-0!../node_modules/thread-loader/dist/cjs.js!../node_modules/ts-loader??ref--13-2!../node_modules/cache-loader/dist/cjs.js??ref--0-0!../node_modules/vue-loader/lib??vue-loader-options!./src/components/DataGrid.vue?vue&type=script&lang=ts& 2:0-49
 @ ./src/components/DataGrid.vue?vue&type=script&lang=ts&
 @ ./src/components/DataGrid.vue
 @ ../node_modules/cache-loader/dist/cjs.js??ref--0-0!../node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue
 @ ./src/main.ts
 @ multi ./src/main.ts
```

seen when running
cd examples
npm install --no-audit
npm run link-packages -- --f vue --examples-version 11.1.0
cd 11.1.0/docs/vue
npm run build --workspaces
```