Fix failing build of the examples (#9179)
* change "code-examples" workflow to run on any commit that changes the examples

only commit to "develop" or manual dispatching will deploy the examples

this solution was copied from https://github.com/handsontable/handsontable/blob/901346eb0609c4cbd2625ef3eb847ebcc1be85a7/.github/workflows/docs-staging.yml#L46

* remove unused "postcss" declaration from package.json

I think that I added it unknowingly when copying from CodeSandbox.

This fixes Vue problem:

```
 ERROR  Failed to compile with 1 error                                                                                                                                                  17:48:35

 error  in ../node_modules/handsontable/dist/handsontable.full.css

Error: No PostCSS Config found in: /Users/warp/www/handsontable/examples/11.1.0/docs/vue/node_modules/handsontable/dist

 @ ../node_modules/cache-loader/dist/cjs.js??ref--13-0!../node_modules/thread-loader/dist/cjs.js!../node_modules/ts-loader??ref--13-2!../node_modules/cache-loader/dist/cjs.js??ref--0-0!../node_modules/vue-loader/lib??vue-loader-options!./src/components/DataGrid.vue?vue&type=script&lang=ts& 2:0-49
 @ ./src/components/DataGrid.vue?vue&type=script&lang=ts&
 @ ./src/components/DataGrid.vue
 @ ../node_modules/cache-loader/dist/cjs.js??ref--0-0!../node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue
 @ ./src/main.ts
 @ multi ./src/main.ts
```

seen when running
cd examples
npm install --no-audit
npm run link-packages -- --f vue --examples-version 11.1.0
cd 11.1.0/docs/vue
npm run build --workspaces
```

* add changelog entry

* fix logical grouping

because I could see that my commit 2c5eeed8916866f33ef2a8ac8ac2adfffc63c93e was deployed to gh-pages, which was not intended

more info: https://docs.github.com/en/actions/learn-github-actions/expressions

* manually fix versions in examples/11.1.0

because they should be respectable Handsontable package versions and I did not know that at the time of writing

this commit will also check if the CI workflow correctly skips the deployment