fix a Babel error due to unclosed <input> in JSX
Module build failed (from ./node_modules/@vuepress/markdown-loader/index.js):
SyntaxError: /Users/warp/www/handsontable/docs/example-named-expressions1.jsx: Expected corresponding JSX closing tag for <input>. (52:6)

  50 |         <input id="named-expressions-input" type="text" value="=10 * Sheet1!$A$2">
  51 |         <button id="named-expressions-button" onClick={(...args) => buttonClickCallback(...args)}>Calculate price</button>
> 52 |       </div>
     |       ^
  53 |
  54 |     </Fragment>
  55 |   );